"""Model registry.

Alembic autogenerate only sees tables that have been imported by the time it
reads ``Base.metadata``. Every new model module must be imported here, and
``alembic/env.py`` imports this package. Forgetting this produces the very
confusing failure mode of an "empty" autogenerated migration.
"""

from app.db.base import Base
from app.db.models.document import EMBEDDING_DIM, Chunk, Document
from app.db.models.request_log import RequestLog

__all__ = ["EMBEDDING_DIM", "Base", "Chunk", "Document", "RequestLog"]
